### ISSUE TITLE
Default Player Controls for tvOS

### ISSUE THREAD

**Issue by amohiy** [kaltura/playkit-ios#313]
##### Prerequisites
- [x] Which Player [version](https://github.com/kaltura/playkit-ios/releases) : 3.6.2 
- [x] Can you reproduce the issue with our latest release version: yes
- [x] Can you reproduce the issue with the latest code from master: yes
- [x] What devices and OS versions are you using: apple tv , tvOS +10

##### Expected behavior
default player controls 

##### Actual behavior
i am trying to use this player on tvOS and i can not find any default controls(play/pause/..) for the player, is this controls view implemented already or should i implement it from my side ?

##### Console output
```
Paste the contents of the Xcode console here.
```

**Comment by x-NR-x** [comment]
Hi @amohiy,

We do not have any default controllers UI for the player. You need to implement that on the app side.
You can see a sample we did here: 
https://github.com/kaltura/playkit-ios-samples/tree/develop/PlayKitAppleTVSample

Thank you,
Nilit

**Comment by amohiy** [comment]
@x-NR-x  Thanks so much.
