### ISSUE TITLE
How to add dependency this library while creating the package?

### ISSUE THREAD

**Issue by knollyReddy** [kaltura/playkit-ios#366]
I want to create a my own player using the playkit. unable to create dependency. please help me out of this.
I have tried this
        **.package(url: "https://github.com/kaltura/playkit-ios.git", from: "3.12.0")**

when I try to generate xcode project, i got this issue

https://github.com/kaltura/playkit-ios.git @ 3.12.0: error: https://github.com/kaltura/playkit-ios.git has no manifest for version 3.12.0

**Comment by noamtamim** [comment]
Sorry, but we don't currently support Swift Package Manager.
