### ISSUE TITLE
Google Chromecast Warning

### ISSUE THREAD

**Issue by onavas** [kaltura/playkit-ios#369]
We've received an email stating the following:

```
Important: Upcoming changes to Google Cast SDK for iOS 13 needed for your app

We are asking all developers to update their iOS apps to the latest version of the Google Cast SDK (v4.4.4) released on August 12, 2019.

With the upcoming release of iOS 13, there are additional privacy controls which will cause new authorization dialogs to appear to users of apps that use the Cast iOS SDK.

We understand that triggering new dialogs may not be ideal for your app. To address this concern and to improve how the SDK works with iOS 13, the Google Cast team implemented changes in our new releases.

We are making two versions of the Cast iOS SDK available to developers,

- One which includes Guest Mode support
The SDK with Guest Mode will prompt a new Bluetooth®-related permission.
- One which excludes Guest Mode support
The SDK without Guest Mode will not prompt any new permissions for Bluetooth®.
In addition, some system-level APIs relating to device discovery will change behaviors in iOS 13, and we will update the Google Cast SDK accordingly. We strongly recommend that you update your apps to the new SDK to avoid a degraded experience on iOS 13.

Additional details can be found at: https://developers.google.com/cast/docs/ios_sender/ios13_changes
```

We don't use Google Cast SDK directly, but through your SDK, so we would make you know that you should update this component as soon as possible.
Is there any new version solving this problem to be released soon? 
Thank you very much,
Oscar

**Comment by x-NR-x** [comment]
Hi Oscar,

Thank you for your response and concern.
Which version of PlayKit are you using?

Regarding the Google Cast, from PlayKit v3.7, it was extracted to its own repo, PlayKitGoogleCast.
The latest version of PlayKitGoogleCast (v1.3.0) has the update to their latest version (v4.4.4), and changes have been done accordingly.

Thanks,
Nilit

**Comment by onavas** [comment]
Hello Nilit,

Thank you very much for your response.
We were using Playkit 3.6.3, so that was the main problem.
We updated the SDK and made the corresponding changes and now it's all working.

Thank you very much,
Oscar

**Comment by x-NR-x** [comment]
Hi @onavas,

Great to hear that it was solved.

Thanks,
Nilit
