### ISSUE TITLE
How to get flavors of video?

### ISSUE THREAD

**Issue by knollyReddy** [kaltura/playkit-ios#370]
##### Prerequisites
- [ ] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-ios/issues): ______
- [ ] Which Player [version](https://github.com/kaltura/playkit-ios/releases) are you using: ______
- [ ] Can you reproduce the issue with our latest release version: ______
- [ ] Can you reproduce the issue with the latest code from master: ______
- [ ] What devices and OS versions are you using: ______
- [ ] If applicable, add test code or test page to reproduce: 
```
Paste test code here
```

##### Expected behavior
What you expected to happen

##### Actual behavior
What actually happened

##### Console output
```
Paste the contents of the Xcode console here.
```
How to get different resolutions of video by using entityId?

**Comment by knollyReddy** [comment]
I want to load different different resolutions of a video. Please help me out it.

**Comment by x-NR-x** [comment]
Hi @knollyReddy,

The resolution of the video is done automatically by the Player.
You can set your preferred value, max BitRate for it to use, as following:
`player.settings.network.preferredPeakBitRate = <value>`

Thanks,
Nilit Danan
