### ISSUE TITLE
Cannot build PlayKit on iOS 13 with Xcode 11.3.1

### ISSUE THREAD

**Issue by bensLine** [kaltura/playkit-ios#394]
I created a sample project with `PlayKit` as a dependency. When I try to run the _xcworkspace_ after `pod install` I get compile errors in `PlayKit`.
I'm using the latest release [3.16.1](https://github.com/kaltura/playkit-ios/releases/tag/v3.16.1) with Xcode 11.3.1 (11C504) for iOS 13.

##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-ios/issues): **yes**
- [x] Which Player [version](https://github.com/kaltura/playkit-ios/releases) are you using: **3.16.1**
- [x] Can you reproduce the issue with our latest release version: **yes**
- [ ] Can you reproduce the issue with the latest code from master: **didn't check, master is behind release 3.16.1**
- [x] What devices and OS versions are you using: **iOS 13, tried to build it on a simulator**
- [x] If applicable, add test code or test page to reproduce: **see example project [KalturaTest.zip](https://github.com/kaltura/playkit-ios/files/4298638/KalturaTest.zip)**

##### Expected behavior
I can use PlayKit as a dependency on an iOS 13 project with Xcode 11.3.1 and Swift 5.1.

##### Actual behavior
PlayKit does not compile as a dependency on an iOS 13 project with Xcode 11.3.1 and Swift 5.1.

![image](https://user-images.githubusercontent.com/5795552/76089730-851c4680-5fba-11ea-8c4b-bc69cbdc2008.png)
...

**Comment by bensLine** [comment]
turned out to be because of a misconfigured pod file. I copied the following from your [documentation](https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/v3_iOS_QuickStart.html) which is also stated in your [Example Podfile](https://github.com/kaltura/playkit-ios/blob/develop/Example/Podfile)
```
post_install do |installer| 
    installer.pods_project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
 	    if target.name == 'PlayKit'
	           config.build_settings['SWIFT_VERSION'] = '4.0'
	    end
        end 
    end 
end
```

Without specifing to build `PlayKit` with `config.build_settings['SWIFT_VERSION'] = '4.0'` it works. 👍 

You might want to go through your documentation and also the links in your Readme, there are several posts and it's not clear to me which one to use. e.g. the following two links provide starting guides with different pod files
https://developer.kaltura.com/player/ios/getting-started-ios
https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/v3_iOS_QuickStart.html

**Comment by x-NR-x** [comment]
Hi @bensLine,

Thank you for contacting us.
I'm glad to hear you succeeded.

This example is deprecated, it's only kept for the test that are in there.
All sample can be found here:
https://github.com/kaltura/playkit-ios-samples

And regarding the documentation, this is the most updated one (the fist you mentioned):
https://developer.kaltura.com/player/ios/getting-started-ios
Updating all documentation we have is a procedure we are going through daily.

Sorry for any inconvenience.

Thanks,
Nilit

**Comment by bensLine** [comment]
Coll, thanks for the clarification Nilit.
Cheers,
Benni
