### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by JaiDeves** [kaltura/playkit-ios#447]
PlayKit by Kaltura is the only restraint for us to use Swift package manager in our project.
We've been waiting for SPM support for a very long time. 
Please provide SPM support.

**Comment by berlisa** [comment]
Hi,
is it planned to make a current SPM Package for the playkit-ios and playkit-ios-providers sdk?

**Comment by x-NR-x** [comment]
Hi @berlisa and @JaiDeves 

Thank you for contacting us.
@JaiDeves sorry for the late response.
The task was in our Backlog, I talked with our team, we will push it to the coming sprint.

Thanks,
Nilit Danan

**Comment by IUFlo** [comment]
Can you please give an update on this! We are still waiting for SPM support!

**Comment by Fredposk** [comment]
@x-NR-x Hi. Any news on this?

**Comment by chausov** [comment]
> @x-NR-x Hi. Any news on this?

Hello, @Fredposk 

We are working on this

Thank you!

**Comment by nivas96** [comment]
Hi @berlisa
Any Update regarding SPM.

**Comment by francodriansetti** [comment]
@x-NR-x Kindly can you share an update on this? Thanks.

**Comment by chausov** [comment]
Hello
Swift Packages for PlayKit and Kava will be available in next two weeks or sooner.

**Comment by chausov** [comment]
PlayKit Swift package now available from version 3.27.1
